CREATE TABLE agences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_grist_id bigint UNIQUE,
  nom text NOT NULL,
  ville text,
  actif boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE adresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_grist_id bigint UNIQUE,
  numero text, voie text, complement text, code_postal text, ville text, departement text,
  adresse_formatee text, latitude numeric(10,7), longitude numeric(10,7), infos_acces text,
  agence_id bigint REFERENCES agences(id) ON DELETE RESTRICT
);

CREATE TABLE utilisateurs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_grist_id bigint UNIQUE,
  nom text NOT NULL, prenom text NOT NULL, email text NOT NULL,
  mot_de_passe_hash text NOT NULL, agence_id bigint REFERENCES agences(id) ON DELETE RESTRICT,
  master_consultant_id bigint REFERENCES utilisateurs(id) ON DELETE SET NULL,
  actif boolean NOT NULL DEFAULT true, derniere_connexion timestamptz,
  doit_changer_mot_de_passe boolean NOT NULL DEFAULT false,
  reset_mot_de_passe_hash text, reset_mot_de_passe_expiration timestamptz,
  progression_formation jsonb NOT NULL DEFAULT '{}'::jsonb,
  session_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX utilisateurs_email_lower_unique ON utilisateurs (lower(email));

CREATE TABLE roles (code text PRIMARY KEY, perimetre text);
CREATE TABLE utilisateur_roles (
  utilisateur_id bigint REFERENCES utilisateurs(id) ON DELETE CASCADE,
  role_code text REFERENCES roles(code) ON DELETE RESTRICT,
  PRIMARY KEY (utilisateur_id, role_code)
);

CREATE TABLE ref_familles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_grist_id bigint UNIQUE, code text NOT NULL UNIQUE, libelle text NOT NULL
);

CREATE TABLE societes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  raison_sociale text NOT NULL, enseigne text, siren text, siret text, code_ape text,
  libelle_ape text, forme_juridique text, capital numeric(18,2), effectif_salarie integer,
  adresse_siege_id bigint REFERENCES adresses(id) ON DELETE SET NULL,
  type_relation text, gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  donnee_exclusive boolean NOT NULL DEFAULT true,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);

CREATE TABLE contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  nom text NOT NULL, prenom text, fonction text, email text, tel text, mobile text,
  societe_id bigint REFERENCES societes(id) ON DELETE SET NULL,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  donnee_exclusive boolean NOT NULL DEFAULT true,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);
ALTER TABLE societes ADD COLUMN contact_principal_id bigint REFERENCES contacts(id) ON DELETE SET NULL;

CREATE TABLE sites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  nom text NOT NULL, adresse_id bigint REFERENCES adresses(id) ON DELETE SET NULL,
  proprietaire_id bigint REFERENCES societes(id) ON DELETE SET NULL,
  type_site text, surface_terrain numeric(14,2), surface_totale numeric(14,2),
  section_cadastrale text, divisible boolean, reserve_fonciere boolean, servitudes text,
  en_bloc boolean, gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);
CREATE TABLE site_parcelles (site_id bigint REFERENCES sites(id) ON DELETE CASCADE, parcelle text, PRIMARY KEY(site_id, parcelle));

CREATE TABLE batiments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  site_id bigint NOT NULL REFERENCES sites(id) ON DELETE RESTRICT, nom text NOT NULL, numero text,
  annee_construction integer, surface_totale numeric(14,2), etat text, divisible boolean,
  copropriete boolean, erp boolean, igh boolean, erp_categorie text, erp_type text,
  destination_plu text, decret_tertiaire boolean,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);

CREATE TABLE cellules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  batiment_id bigint NOT NULL REFERENCES batiments(id) ON DELETE RESTRICT, nom text NOT NULL,
  numero text, surface numeric(14,2), etage text,
  type_bien_id bigint REFERENCES ref_familles(id) ON DELETE RESTRICT,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);

CREATE TABLE lots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  nom text NOT NULL, numero text, site_id bigint REFERENCES sites(id) ON DELETE RESTRICT,
  surface numeric(14,2), divisible boolean, nombre_parking integer, en_bloc boolean,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);
CREATE TABLE lot_cellules (lot_id bigint REFERENCES lots(id) ON DELETE CASCADE, cellule_id bigint REFERENCES cellules(id) ON DELETE RESTRICT, PRIMARY KEY(lot_id, cellule_id));

CREATE TABLE ref_categories_caracteristiques (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  libelle text NOT NULL UNIQUE, ordre integer NOT NULL
);
CREATE TABLE ref_caracteristiques (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  libelle text NOT NULL, categorie_id bigint REFERENCES ref_categories_caracteristiques(id) ON DELETE RESTRICT,
  type_valeur text NOT NULL CHECK (type_valeur IN ('bool','nombre','texte','liste')), unite text, ordre integer
);
CREATE TABLE ref_caracteristique_familles (caracteristique_id bigint REFERENCES ref_caracteristiques(id) ON DELETE CASCADE, famille_id bigint REFERENCES ref_familles(id) ON DELETE CASCADE, PRIMARY KEY(caracteristique_id, famille_id));
CREATE TABLE ref_caracteristique_niveaux (caracteristique_id bigint REFERENCES ref_caracteristiques(id) ON DELETE CASCADE, niveau text CHECK(niveau IN ('batiment','cellule','lot')), PRIMARY KEY(caracteristique_id, niveau));
CREATE TABLE caracteristiques_bien (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  caracteristique_id bigint NOT NULL REFERENCES ref_caracteristiques(id) ON DELETE RESTRICT,
  niveau text NOT NULL CHECK(niveau IN ('batiment','cellule','lot')),
  batiment_id bigint REFERENCES batiments(id) ON DELETE CASCADE,
  cellule_id bigint REFERENCES cellules(id) ON DELETE CASCADE,
  lot_id bigint REFERENCES lots(id) ON DELETE CASCADE,
  valeur_bool boolean, valeur_nombre numeric(18,4), valeur_texte text,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT,
  CHECK (num_nonnulls(batiment_id, cellule_id, lot_id) = 1)
);

CREATE TABLE offres (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  numero text, nom text NOT NULL, lot_id bigint NOT NULL REFERENCES lots(id) ON DELETE RESTRICT,
  nature text NOT NULL CHECK(nature IN ('vente','location','vente_et_location')),
  type_contrat text, occupation text, stade_commercialisation text,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);
CREATE TABLE offre_co_gestionnaires (offre_id bigint REFERENCES offres(id) ON DELETE CASCADE, utilisateur_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT, PRIMARY KEY(offre_id, utilisateur_id));
CREATE TABLE conditions_financieres (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  offre_id bigint NOT NULL REFERENCES offres(id) ON DELETE CASCADE,
  type text NOT NULL CHECK(type IN ('vente','location')), prix_vente numeric(18,2),
  loyer_ht_m2_an numeric(18,2), loyer_global_an numeric(18,2), charges_ht_m2_an numeric(18,2),
  depot_garantie numeric(18,2), taxe_fonciere numeric(18,2), teom numeric(18,2), cfe numeric(18,2),
  taux_net_initial numeric(8,4), taux_net_potentiel numeric(8,4), disponibilite date,
  UNIQUE(offre_id, type)
);

CREATE TABLE mandats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  numero text, numero_registre text, offre_id bigint REFERENCES offres(id) ON DELETE RESTRICT,
  societe_mandante_id bigint REFERENCES societes(id) ON DELETE RESTRICT, type text, nature text,
  avancement text, date_debut date, date_fin date, honoraires_mode text,
  honoraires_montant numeric(18,2), honoraires_charge text,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  donnee_exclusive boolean NOT NULL DEFAULT true,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);

CREATE TABLE demandes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  societe_id bigint REFERENCES societes(id) ON DELETE RESTRICT,
  contact_id bigint REFERENCES contacts(id) ON DELETE RESTRICT, nature_transaction text,
  surface_min numeric(14,2), surface_max numeric(14,2), budget_min numeric(18,2), budget_max numeric(18,2),
  secteur_geo text, criteres_specifiques text,
  gestionnaire_id bigint REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  donnee_exclusive boolean NOT NULL DEFAULT true,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT
);
CREATE TABLE demande_familles (demande_id bigint REFERENCES demandes(id) ON DELETE CASCADE, famille_id bigint REFERENCES ref_familles(id) ON DELETE RESTRICT, PRIMARY KEY(demande_id, famille_id));

CREATE TABLE matching_demandes_lots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  demande_id bigint NOT NULL REFERENCES demandes(id) ON DELETE CASCADE,
  lot_id bigint NOT NULL REFERENCES lots(id) ON DELETE CASCADE,
  score_surface numeric(6,2), score_budget numeric(6,2), score_geographie numeric(6,2),
  score_transaction numeric(6,2), score_type_bien numeric(6,2), score_global numeric(6,2),
  scores_detail jsonb, historique boolean NOT NULL DEFAULT true,
  UNIQUE(demande_id, lot_id)
);

CREATE TABLE traitements_agents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, legacy_grist_id bigint UNIQUE,
  suivi_id text NOT NULL UNIQUE, agent text NOT NULL, objet_type text NOT NULL, objet_id bigint NOT NULL,
  statut_traitement text NOT NULL CHECK(statut_traitement IN ('en_attente','en_cours','termine','erreur')),
  resultat jsonb, message_erreur text,
  agence_id bigint NOT NULL REFERENCES agences(id) ON DELETE RESTRICT,
  user_id bigint NOT NULL REFERENCES utilisateurs(id) ON DELETE RESTRICT,
  date_creation timestamptz NOT NULL DEFAULT now(), date_mise_a_jour timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
  sid varchar PRIMARY KEY,
  sess json NOT NULL,
  expire timestamp(6) NOT NULL
);
CREATE INDEX sessions_expire_idx ON sessions(expire);

INSERT INTO roles(code, perimetre) VALUES
  ('consultant','proprietaire'), ('master_consultant','equipe'), ('directeur_agence','agence'),
  ('admin_agence','agence_admin'), ('super_admin','plateforme_admin')
ON CONFLICT (code) DO NOTHING;
