ALTER TABLE lots
  ADD COLUMN IF NOT EXISTS batiment_id bigint REFERENCES batiments(id) ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS import_grist_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode text NOT NULL CHECK (mode IN ('validation', 'import')),
  statut text NOT NULL CHECK (statut IN ('en_cours', 'reussi', 'rejete')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  source_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  target_counts jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS import_grist_rejections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES import_grist_runs(id) ON DELETE CASCADE,
  source_table text NOT NULL,
  legacy_grist_id bigint,
  code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS import_grist_table_counts (
  run_id bigint NOT NULL REFERENCES import_grist_runs(id) ON DELETE CASCADE,
  source_table text NOT NULL,
  source_count integer NOT NULL,
  imported_count integer NOT NULL,
  rejected_count integer NOT NULL,
  PRIMARY KEY (run_id, source_table)
);

CREATE INDEX IF NOT EXISTS lots_batiment_id_idx ON lots(batiment_id);
CREATE INDEX IF NOT EXISTS import_grist_rejections_run_idx ON import_grist_rejections(run_id);
