import { useId } from 'react';
import { ChevronLeft, ChevronRight, HelpCircle, Search, X } from 'lucide-react';

const cx = (...classes) => classes.filter(Boolean).join(' ');

const variants = {
  primary: 'bg-oriana-violet text-white hover:bg-oriana-violet/90 shadow-oriana',
  secondary: 'border border-oriana-bordure bg-oriana-surface text-oriana-texte hover:bg-oriana-surfaceAlt',
  ghost: 'text-oriana-discret hover:bg-oriana-surfaceAlt hover:text-oriana-texte',
};

export function Button({ variant = 'primary', size = 'md', className, children, ...props }) {
  return <button type="button" className={cx('inline-flex items-center justify-center gap-2 rounded-oriana font-semibold transition duration-oriana disabled:cursor-not-allowed disabled:opacity-50', variants[variant], size === 'sm' ? 'min-h-9 px-3 text-xs' : 'min-h-11 px-4 text-sm', className)} {...props}>{children}</button>;
}

export function Card({ className, children, ...props }) { return <section className={cx('rounded-oriana border border-oriana-bordure bg-oriana-surface p-5 shadow-oriana', className)} {...props}>{children}</section>; }

export function Field({ label, hint, error, children }) { return <label className="grid gap-1.5 text-sm"><span className="font-semibold text-oriana-texte">{label}</span>{children}{(error || hint) && <span className={error ? 'text-oriana-lavandeMoyen' : 'text-xs text-oriana-discret'}>{error || hint}</span>}</label>; }
const control = 'min-h-11 w-full rounded-oriana border border-oriana-bordure bg-oriana-fond px-3 py-2 text-sm text-oriana-texte placeholder:text-oriana-discret/70 transition focus:border-oriana-violet focus:outline-none';
export function Input({ className, ...props }) { return <input className={cx(control, className)} {...props} />; }
export function Textarea({ className, ...props }) { return <textarea className={cx(control, 'min-h-24 resize-y', className)} {...props} />; }
export function Select({ className, children, ...props }) { return <select className={cx(control, className)} {...props}>{children}</select>; }

export function Checkbox({ label, ...props }) { return <label className="inline-flex items-center gap-2 text-sm"><input type="checkbox" className="h-4 w-4 accent-oriana-violet" {...props}/>{label}</label>; }
export function Radio({ label, ...props }) { return <label className="inline-flex items-center gap-2 text-sm"><input type="radio" className="h-4 w-4 accent-oriana-violet" {...props}/>{label}</label>; }
export function Toggle({ checked, onChange, label }) { return <label className="inline-flex cursor-pointer items-center gap-3 text-sm"><button type="button" role="switch" aria-checked={checked} onClick={() => onChange?.(!checked)} className={cx('relative h-6 w-11 rounded-full transition', checked ? 'bg-oriana-violet' : 'bg-oriana-bordure')}><span className={cx('absolute top-1 h-4 w-4 rounded-full bg-white transition', checked ? 'left-6' : 'left-1')}/></button>{label}</label>; }

export function Badge({ children, variant = 'default' }) { return <span className={cx('inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold', variant === 'accent' ? 'border-oriana-violet/20 bg-oriana-violet/10 text-oriana-violet' : 'border-oriana-bordure bg-oriana-surfaceAlt text-oriana-discret')}>{children}</span>; }
export function Tooltip({ label, children }) { return <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 z-50 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-md bg-oriana-fondAlt px-2 py-1 text-xs text-white shadow-oriana-lg group-hover:block group-focus-within:block">{label}</span></span>; }

export function Modal({ open, onClose, title, children }) { const id = useId(); if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-oriana-fondAlt/75 p-4" role="presentation" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby={id} className="animate-enter w-full max-w-lg rounded-oriana border border-oriana-bordure bg-oriana-surface p-6 shadow-oriana-lg" onMouseDown={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 id={id} className="font-titre text-xl">{title}</h2><Button variant="ghost" size="sm" aria-label="Fermer" onClick={onClose}><X size={18}/></Button></div>{children}</div></div>; }
export function Drawer({ open, onClose, title, children }) { const id = useId(); if (!open) return null; return <div className="fixed inset-0 z-50 bg-oriana-fondAlt/70" role="presentation" onMouseDown={onClose}><aside role="dialog" aria-modal="true" aria-labelledby={id} className="animate-enter ml-auto h-full w-full max-w-md border-l border-oriana-bordure bg-oriana-surface p-6 shadow-oriana-lg" onMouseDown={(event) => event.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 id={id} className="font-titre text-xl">{title}</h2><Button variant="ghost" size="sm" onClick={onClose} aria-label="Fermer"><X size={18}/></Button></div>{children}</aside></div>; }

export function Table({ columns, rows }) { return <div className="overflow-x-auto rounded-oriana border border-oriana-bordure"><table className="w-full text-left text-sm"><thead className="bg-oriana-surfaceAlt text-xs uppercase tracking-wide text-oriana-discret"><tr>{columns.map((column) => <th className="px-4 py-3" key={column.key}>{column.label}</th>)}</tr></thead><tbody className="divide-y divide-oriana-bordure">{rows.map((row, index) => <tr className="hover:bg-oriana-surfaceAlt/60" key={row.id || index}>{columns.map((column) => <td className="px-4 py-3" key={column.key}>{column.render ? column.render(row) : row[column.key]}</td>)}</tr>)}</tbody></table></div>; }
export function Pagination({ page = 1, total = 1, onChange }) { return <nav aria-label="Pagination" className="flex items-center justify-between gap-3 text-sm"><Button variant="secondary" size="sm" disabled={page <= 1} onClick={() => onChange?.(page - 1)}><ChevronLeft size={15}/>Précédent</Button><span className="text-oriana-discret">Page {page} sur {total}</span><Button variant="secondary" size="sm" disabled={page >= total} onClick={() => onChange?.(page + 1)}>Suivant<ChevronRight size={15}/></Button></nav>; }
export function Avatar({ name = 'Utilisateur', src }) { const initials = name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase(); return src ? <img className="h-9 w-9 rounded-full object-cover" src={src} alt={name}/> : <span aria-label={name} className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-oriana-lavandeMoyen to-oriana-violet text-xs font-bold text-white">{initials}</span>; }
export function SearchBar({ className, ...props }) { return <div className={cx('relative', className)}><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-oriana-discret" size={17}/><Input className="pl-10" type="search" aria-label="Recherche" {...props}/></div>; }
export function Notification({ title, description }) { return <div role="status" className="flex gap-3 rounded-oriana border border-oriana-lavande/40 bg-oriana-surface p-4 shadow-oriana"><span className="mt-1 h-2 w-2 rounded-full bg-oriana-lavandeMoyen"/><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-oriana-discret">{description}</p></div></div>; }
export function Loader({ label = 'Chargement' }) { return <div role="status" className="inline-flex items-center gap-2 text-sm text-oriana-discret"><span className="h-4 w-4 animate-spin rounded-full border-2 border-oriana-bordure border-t-oriana-lavande"/><span>{label}</span></div>; }
export function Skeleton({ className }) { return <span aria-hidden="true" className={cx('relative block h-4 overflow-hidden rounded bg-oriana-surfaceAlt', className)}><span className="absolute inset-0 -translate-x-full animate-[shimmer_1.5s_infinite] bg-gradient-to-r from-transparent via-oriana-lavande/15 to-transparent"/></span>; }
export function EmptyState({ title, description, action }) { return <div className="grid min-h-52 place-items-center rounded-oriana border border-dashed border-oriana-bordure p-8 text-center"><div><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-full bg-oriana-violet/15 text-oriana-lavande"><Search size={20}/></div><h3 className="font-titre text-lg">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm text-oriana-discret">{description}</p>{action && <div className="mt-5">{action}</div>}</div></div>; }

export function Tabs({ tabs, active, onChange }) { return <div role="tablist" className="flex gap-1 overflow-x-auto border-b border-oriana-bordure">{tabs.map((tab) => <button type="button" role="tab" aria-selected={active === tab.id} tabIndex={active === tab.id ? 0 : -1} className={cx('min-h-11 whitespace-nowrap border-b-2 px-3 py-2 text-sm font-semibold transition', active === tab.id ? 'border-oriana-violet text-oriana-violet' : 'border-transparent text-oriana-discret hover:text-oriana-texte')} onClick={() => onChange?.(tab.id)} key={tab.id}>{tab.label}</button>)}</div>; }
export function Accordion({ items, openId, onChange }) { return <div className="divide-y divide-oriana-bordure rounded-oriana border border-oriana-bordure">{items.map((item) => <div key={item.id}><button type="button" className="flex min-h-11 w-full items-center justify-between p-4 text-left font-semibold" aria-expanded={openId === item.id} onClick={() => onChange?.(openId === item.id ? null : item.id)}>{item.title}<ChevronRight size={17} className={cx('transition', openId === item.id && 'rotate-90')}/></button>{openId === item.id && <div className="px-4 pb-4 text-sm text-oriana-discret">{item.content}</div>}</div>)}</div>; }
export function Toolbar({ children }) { return <div className="flex flex-wrap items-center justify-between gap-3 rounded-oriana border border-oriana-bordure bg-oriana-surface p-3">{children}</div>; }
export function Breadcrumb({ items }) { return <nav aria-label="Fil d’Ariane"><ol className="flex flex-wrap items-center gap-2 text-xs text-oriana-discret">{items.map((item, index) => <li className="flex items-center gap-2" key={item}>{index > 0 && <ChevronRight size={12}/>}<span aria-current={index === items.length - 1 ? 'page' : undefined}>{item}</span></li>)}</ol></nav>; }
export function PageHeader({ eyebrow, title, description, actions }) { return <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-3"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-oriana-violet">{eyebrow}</p><span className="h-px w-12 bg-oriana-violet/35"/></div><h1 className="font-titre text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1><p className="mt-1.5 max-w-2xl text-sm leading-6 text-oriana-discret">{description}</p></div>{actions && <div className="flex w-full flex-wrap gap-2 md:w-auto md:justify-end">{actions}</div>}</header>; }
export function HelpButton({ onClick }) { return <Tooltip label="Aide contextuelle"><Button variant="secondary" size="sm" aria-label="Ouvrir l’aide" onClick={onClick}><HelpCircle size={17}/>Aide</Button></Tooltip>; }
