import { useEffect, useMemo, useState } from 'react';
import { BadgeEuro, Download, Mail, MapPin, Pencil, Phone, Plus, RefreshCw, Ruler, Truck, Warehouse } from 'lucide-react';
import { offresApi } from '../api/offres';
import { Badge, Breadcrumb, Button, Card, Drawer, EmptyState, Field, Input, Loader, Notification, PageHeader, Select } from '../components/ui';

const natureLabels = { vente: 'Vente', location: 'Location', vente_et_location: 'Vente & location' };
const conditionTypes = (nature) => nature === 'vente_et_location' ? ['vente', 'location'] : [nature];
const money = (value) => value || value === 0 ? `${Number(value).toLocaleString('fr-FR')} €` : 'À renseigner';
const optionalNumber = (value) => value === '' ? undefined : Number(value);

function OfferEditor({ record, lots, pending, onCancel, onSave }) {
  const [form, setForm] = useState({ numero: record?.numero || '', nom: record?.nom || '', lot_id: record?.lot_id || '', nature: record?.nature || 'vente', type_contrat: record?.type_contrat || '', occupation: record?.occupation || 'libre', stade_commercialisation: record?.stade_commercialisation || '' });
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom"><Input autoFocus value={form.nom} onChange={(event) => set('nom', event.target.value)}/></Field><Field label="Numéro"><Input value={form.numero} onChange={(event) => set('numero', event.target.value)}/></Field></div><Field label="Lot commercialisé"><Select value={form.lot_id} onChange={(event) => set('lot_id', event.target.value)}><option value="">Sélectionner un lot</option>{lots.map((lot) => <option key={lot.id} value={lot.id}>{lot.nom || `Lot #${lot.id}`}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Nature"><Select value={form.nature} onChange={(event) => set('nature', event.target.value)}><option value="vente">Vente</option><option value="location">Location</option><option value="vente_et_location">Vente & location</option></Select></Field><Field label="Occupation"><Select value={form.occupation} onChange={(event) => set('occupation', event.target.value)}><option value="libre">Libre</option><option value="occupe">Occupé</option></Select></Field><Field label="Type de contrat"><Input value={form.type_contrat} onChange={(event) => set('type_contrat', event.target.value)}/></Field><Field label="Stade de commercialisation"><Input value={form.stade_commercialisation} onChange={(event) => set('stade_commercialisation', event.target.value)}/></Field></div><div className="flex justify-end gap-2 border-t border-oriana-bordure pt-4"><Button variant="secondary" onClick={onCancel}>Annuler</Button><Button disabled={!form.lot_id || pending} onClick={() => onSave({ ...form, lot_id: Number(form.lot_id) })}>{pending ? 'Enregistrement…' : 'Enregistrer l’offre'}</Button></div></div>;
}

function ConditionCard({ type, offerId, record, onSaved }) {
  const [editing, setEditing] = useState(!record);
  const [pending, setPending] = useState(false);
  const [form, setForm] = useState({ prix_vente: record?.prix_vente ?? '', loyer_ht_m2_an: record?.loyer_ht_m2_an ?? '', loyer_global_an: record?.loyer_global_an ?? '', charges_ht_m2_an: record?.charges_ht_m2_an ?? '', depot_garantie: record?.depot_garantie ?? '', taxe_fonciere: record?.taxe_fonciere ?? '', teom: record?.teom ?? '', cfe: record?.cfe ?? '', taux_net_initial: record?.taux_net_initial ?? '', taux_net_potentiel: record?.taux_net_potentiel ?? '', disponibilite: record?.disponibilite || '' });
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  async function save() { setPending(true); const data = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '').map(([field, value]) => [field, field === 'disponibilite' ? value : optionalNumber(value)])); try { if (record) await offresApi.updateCondition(record.id, data); else await offresApi.createCondition({ offre_id: offerId, type, ...data }); setEditing(false); await onSaved(); } finally { setPending(false); } }
  return <Card className="shadow-none"><div className="flex items-center justify-between"><div><Badge variant="accent">{natureLabels[type]}</Badge><h3 className="mt-2 font-titre text-xl">Conditions de {type}</h3></div>{record && !editing && <Button variant="ghost" size="sm" onClick={() => setEditing(true)}><Pencil size={15}/>Modifier</Button>}</div>{!editing ? <div className="mt-5 grid gap-3 sm:grid-cols-2"><p className="text-sm"><span className="block text-xs text-oriana-discret">{type === 'vente' ? 'Prix de vente' : 'Loyer HT/m²/an'}</span><strong>{type === 'vente' ? money(record?.prix_vente) : money(record?.loyer_ht_m2_an)}</strong></p><p className="text-sm"><span className="block text-xs text-oriana-discret">Disponibilité</span><strong>{record?.disponibilite || 'À préciser'}</strong></p></div> : <div className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-2">{type === 'vente' ? <Field label="Prix de vente (€)"><Input type="number" min="0" value={form.prix_vente} onChange={(event) => set('prix_vente', event.target.value)}/></Field> : <><Field label="Loyer HT/m²/an (€)"><Input type="number" min="0" value={form.loyer_ht_m2_an} onChange={(event) => set('loyer_ht_m2_an', event.target.value)}/></Field><Field label="Loyer global annuel (€)"><Input type="number" min="0" value={form.loyer_global_an} onChange={(event) => set('loyer_global_an', event.target.value)}/></Field><Field label="Charges HT/m²/an (€)"><Input type="number" min="0" value={form.charges_ht_m2_an} onChange={(event) => set('charges_ht_m2_an', event.target.value)}/></Field><Field label="Dépôt de garantie (€)"><Input type="number" min="0" value={form.depot_garantie} onChange={(event) => set('depot_garantie', event.target.value)}/></Field></>}<Field label="Taxe foncière (€)"><Input type="number" min="0" value={form.taxe_fonciere} onChange={(event) => set('taxe_fonciere', event.target.value)}/></Field><Field label="TEOM (€)"><Input type="number" min="0" value={form.teom} onChange={(event) => set('teom', event.target.value)}/></Field><Field label="CFE (€)"><Input type="number" min="0" value={form.cfe} onChange={(event) => set('cfe', event.target.value)}/></Field>{type === 'vente' && <><Field label="Taux net initial (%)"><Input type="number" step="any" value={form.taux_net_initial} onChange={(event) => set('taux_net_initial', event.target.value)}/></Field><Field label="Taux net potentiel (%)"><Input type="number" step="any" value={form.taux_net_potentiel} onChange={(event) => set('taux_net_potentiel', event.target.value)}/></Field></>}<Field label="Disponibilité"><Input value={form.disponibilite} onChange={(event) => set('disponibilite', event.target.value)}/></Field></div><div className="flex justify-end gap-2">{record && <Button variant="secondary" onClick={() => setEditing(false)}>Annuler</Button>}<Button disabled={pending} onClick={save}>{pending ? 'Enregistrement…' : 'Enregistrer les conditions'}</Button></div></div>}</Card>;
}

const surfaces = [
  ['2', 'Bureaux', '512 m²'],
  ['1', 'Bureaux', '523 m²'],
  ['RDC', 'Bureaux', '182 m²'],
  ['RDC', 'Entrepôts', '4 151 m²'],
];

function DataRow({ label, children, strong = false }) {
  return <div className="grid grid-cols-[minmax(115px,42%)_1fr] gap-3 py-1 text-sm"><dt className="text-oriana-discret">{label}</dt><dd className={strong ? 'font-bold text-oriana-texte' : 'font-medium text-oriana-texte'}>{children}</dd></div>;
}

function Section({ title, children, className = '' }) {
  return <section className={`rounded-oriana border border-oriana-bordure bg-oriana-surface ${className}`}><div className="border-b border-oriana-bordure px-5 py-3"><h3 className="text-xs font-bold uppercase tracking-[.12em] text-oriana-texte">{title}</h3></div><div className="p-5">{children}</div></section>;
}

function RichOfferDetail({ selected, conditions = selected.conditions || [], onEdit, onSaved = async () => {} }) {
  const [activeTab, setActiveTab] = useState('synthese');
  const isSale = selected.nature === 'vente' || selected.nature === 'vente_et_location';
  const isRental = selected.nature === 'location' || selected.nature === 'vente_et_location';
  const tabs = [['synthese', 'Synthèse'], ['bien', 'Bien & surfaces'], ['finances', isSale && isRental ? 'Vente & location' : 'Finances'], ['mandats', 'Mandats'], ['actions', 'Actions'], ['visites', 'Visites'], ['documents', 'Documents'], ['transactions', 'Transactions']];
  const synthesisVisible = activeTab === 'synthese';
  return <div className="space-y-4">
    <Card className="p-0 overflow-hidden">
      <div className="flex flex-col gap-4 border-b border-oriana-bordure px-5 py-4 sm:flex-row sm:items-start sm:justify-between">
        <div><div className="flex flex-wrap items-center gap-2"><Badge variant="accent">{isSale && isRental ? 'À vendre ou à louer' : isSale ? 'À vendre' : 'À louer'}</Badge><Badge>Réf. {selected.numero || '1240613'}</Badge></div><h2 className="mt-3 font-titre text-2xl sm:text-3xl">{selected.nom || 'Bureaux et entrepôts'}</h2><p className="mt-2 flex items-center gap-2 text-sm text-oriana-discret"><MapPin size={15}/>23, rue Ambroise Croizat · 95190 Goussainville</p></div>
        <div className="flex gap-2"><Button variant="secondary"><Download size={16}/>Exporter</Button><Button onClick={onEdit}><Pencil size={16}/>Modifier</Button></div>
      </div>
      <div className="grid lg:grid-cols-[minmax(280px,.85fr)_1.4fr]">
        <div className="relative min-h-64 bg-[#1A0E24]"><img src="/assets/warehouse-goussainville.png" alt="Entrepôt de Goussainville" className="h-full min-h-64 w-full object-cover"/><div className="absolute bottom-3 left-3 rounded-full bg-[#1A0E24]/90 px-3 py-1.5 text-xs font-bold text-white">1 / 6 photos</div></div>
        <div className="grid gap-4 p-5 sm:grid-cols-3 lg:grid-cols-2 xl:grid-cols-3">
          <div><Ruler size={18} className="text-oriana-lavande"/><p className="mt-3 text-xs text-oriana-discret">Surface totale</p><p className="mt-1 text-xl font-bold">5 368 m²</p><p className="mt-1 text-xs text-oriana-discret">Non divisible</p></div>
          <div><Warehouse size={18} className="text-oriana-lavande"/><p className="mt-3 text-xs text-oriana-discret">Configuration</p><p className="mt-1 text-xl font-bold">Indépendant</p><p className="mt-1 text-xs text-oriana-discret">Site sécurisé</p></div>
          <div><Truck size={18} className="text-oriana-lavande"/><p className="mt-3 text-xs text-oriana-discret">Accès marchandises</p><p className="mt-1 text-xl font-bold">21 quais</p><p className="mt-1 text-xs text-oriana-discret">1 porte plain-pied</p></div>
          <div className="sm:col-span-3 lg:col-span-2 xl:col-span-3 grid gap-3 rounded-oriana bg-oriana-violet/10 p-4 sm:grid-cols-2">
            {isSale && <div><p className="text-xs font-bold uppercase tracking-wider text-oriana-lavande">Prix de vente</p><p className="mt-1 font-titre text-2xl">7 000 000 € <span className="text-sm font-sans text-oriana-discret">/ HD</span></p></div>}
            {isRental && <div><p className="text-xs font-bold uppercase tracking-wider text-oriana-lavande">Loyer annuel</p><p className="mt-1 font-titre text-2xl">145 € <span className="text-sm font-sans text-oriana-discret">HT/m²/an</span></p></div>}
          </div>
        </div>
      </div>
    </Card>

    <nav aria-label="Vues de l’offre" className="flex gap-1 overflow-x-auto rounded-oriana border border-oriana-bordure bg-oriana-surface p-1">
      {tabs.map(([id, label]) => <button key={id} type="button" aria-current={activeTab === id ? 'page' : undefined} onClick={() => setActiveTab(id)} className={`whitespace-nowrap rounded-md px-4 py-2 text-sm font-semibold ${activeTab === id ? 'bg-oriana-violet text-white' : 'text-oriana-discret hover:bg-oriana-surfaceAlt'}`}>{label}</button>)}
    </nav>

    {(synthesisVisible || activeTab === 'bien') && <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]">
      <Section title="Équipements et prestations">
        <div className="grid gap-x-8 md:grid-cols-2"><dl><DataRow label="Site">Indépendant sécurisé</DataRow><DataRow label="Entrepôt">Quais</DataRow><DataRow label="Clôture">Grillage</DataRow><DataRow label="Ossature">Métallique</DataRow><DataRow label="Murs">Bardage simple</DataRow><DataRow label="Couverture">Bac acier isolé</DataRow></dl><dl><DataRow label="Bureaux">Cloisons, faux-plafonds</DataRow><DataRow label="Chauffage">Électrique</DataRow><DataRow label="Réseaux">Câblage et fibre optique</DataRow><DataRow label="Hauteur libre">8,04 à 8,66 m</DataRow><DataRow label="Accès">Gros porteurs</DataRow><DataRow label="Parking">Oui</DataRow></dl></div>
      </Section>
      <Section title="Surfaces">
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-oriana-bordure text-xs text-oriana-discret"><th className="pb-2 font-semibold">Étage</th><th className="pb-2 font-semibold">Usage</th><th className="pb-2 text-right font-semibold">Surface</th></tr></thead><tbody>{surfaces.map((row) => <tr key={`${row[0]}-${row[1]}`} className="border-b border-oriana-bordure/70 last:border-0"><td className="py-2.5">{row[0]}</td><td className="py-2.5">{row[1]}</td><td className="py-2.5 text-right font-semibold">{row[2]}</td></tr>)}</tbody><tfoot><tr><td colSpan="2" className="pt-3 font-bold">Total général</td><td className="pt-3 text-right font-bold">5 368 m²</td></tr></tfoot></table></div>
      </Section>
      <Section title="Conditions financières et juridiques">
        <dl className="grid gap-x-8 md:grid-cols-2"><div>{isSale && <DataRow label="Prix de vente" strong>7 000 000 € / HD</DataRow>}{isRental && <DataRow label="Loyer" strong>145 € HT/m²/an</DataRow>}<DataRow label="Taxe foncière">66 000 €</DataRow><DataRow label="Taxe bureaux">12 000 €</DataRow></div><div><DataRow label="Honoraires">{isRental && !isSale ? '15 % HT du loyer annuel' : '5 % HT, charge acquéreur'}</DataRow><DataRow label="Régime fiscal">{isRental && !isSale ? 'TVA sur loyers' : 'Droits de mutation'}</DataRow><DataRow label="DPE">En cours de détermination</DataRow></div></dl>
      </Section>
      <Section title="Localisation et accès">
        <div className="rounded-oriana bg-oriana-surfaceAlt p-4"><div className="flex items-start gap-3"><span className="rounded-full bg-oriana-violet p-2 text-white"><MapPin size={17}/></span><div><p className="font-bold">Goussainville · Val-d’Oise</p><p className="mt-1 text-sm leading-5 text-oriana-discret">Accès rapide A1, A3 et Francilienne. Proximité immédiate de l’aéroport Paris–Charles-de-Gaulle.</p></div></div><Button variant="secondary" className="mt-4 w-full">Ouvrir la carte</Button></div>
      </Section>
    </div>}
    {activeTab === 'finances' && <div className={`grid gap-4 ${isSale && isRental ? 'lg:grid-cols-2' : ''}`}>{conditionTypes(selected.nature).map((type) => <ConditionCard key={`${selected.id}-${type}`} type={type} offerId={selected.id} record={conditions.find((item) => Number(item.offre_id) === Number(selected.id) && item.type === type)} onSaved={onSaved}/>)}</div>}
    {activeTab === 'mandats' && <Section title="Mandats liés à l’offre"><div className="rounded-oriana border border-oriana-bordure p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Mandat {isSale && isRental ? 'de vente et location' : isSale ? 'de vente' : 'de location'} n° 2024-0613</p><p className="mt-1 text-sm text-oriana-discret">Mandat simple · Alliance Entreprise et Commerce</p></div><Badge variant="accent">Actif</Badge></div></div><Button className="mt-4"><Plus size={15}/>Ajouter un mandat</Button></Section>}
    {activeTab === 'actions' && <Section title="Actions commerciales"><div className="space-y-3">{['Relancer le propriétaire pour le DPE', 'Préparer le dossier de commercialisation', 'Qualifier les acquéreurs intéressés'].map((action, index) => <div key={action} className="flex items-center justify-between gap-4 rounded-oriana border border-oriana-bordure p-3"><div><p className="text-sm font-semibold">{action}</p><p className="mt-1 text-xs text-oriana-discret">{index === 0 ? 'À faire aujourd’hui' : 'À planifier'}</p></div><Button size="sm" variant="secondary">Ouvrir</Button></div>)}</div><Button className="mt-4"><Plus size={15}/>Nouvelle action</Button></Section>}
    {activeTab === 'visites' && <Section title="Visites"><div className="rounded-oriana bg-oriana-surfaceAlt p-5 text-center"><p className="font-bold">Aucune visite planifiée</p><p className="mt-1 text-sm text-oriana-discret">Planifiez une visite et associez-la à un contact ou une société.</p><Button className="mt-4"><Plus size={15}/>Planifier une visite</Button></div></Section>}
    {activeTab === 'documents' && <Section title="Documents"><div className="grid gap-3 md:grid-cols-2"><div className="rounded-oriana border border-oriana-bordure p-4"><p className="font-bold">Fiche de commercialisation</p><p className="mt-1 text-xs text-oriana-discret">PDF · mise à jour le 07/10/2024</p></div><div className="rounded-oriana border border-oriana-bordure p-4"><p className="font-bold">Dossier technique</p><p className="mt-1 text-xs text-oriana-discret">3 documents disponibles</p></div></div><Button className="mt-4"><Plus size={15}/>Ajouter un document</Button></Section>}
    {activeTab === 'transactions' && <Section title={isSale && isRental ? 'Transactions et négociations' : isSale ? 'Négociations de vente' : 'Négociations locatives'}><div className="rounded-oriana bg-oriana-surfaceAlt p-5 text-center"><p className="font-bold">Aucune transaction enregistrée</p><p className="mt-1 text-sm text-oriana-discret">Les propositions, contre-propositions et signatures apparaîtront ici.</p><Button className="mt-4"><Plus size={15}/>Démarrer une négociation</Button></div></Section>}
    {synthesisVisible && <div className={`grid gap-4 ${isSale && isRental ? 'lg:grid-cols-2' : ''}`}>{conditionTypes(selected.nature).map((type) => <ConditionCard key={`summary-${selected.id}-${type}`} type={type} offerId={selected.id} record={conditions.find((item) => Number(item.offre_id) === Number(selected.id) && item.type === type)} onSaved={onSaved}/>)}</div>}
    {synthesisVisible && <Section title="Votre contact"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Denis Palais</p><p className="mt-1 text-sm text-oriana-discret">Consultant immobilier d’entreprise</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary"><Phone size={16}/>Appeler</Button><Button><Mail size={16}/>Envoyer un e-mail</Button></div></div></Section>}
  </div>;
}

export function OffresPage() {
  const [data, setData] = useState({ offers: [], conditions: [], lots: [] });
  const [selectedId, setSelectedId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [editor, setEditor] = useState(null);
  const [pending, setPending] = useState(false);
  async function load() { setError(''); try { const result = await offresApi.listAll(); setData(result); setSelectedId((current) => current || result.offers[0]?.id || null); } catch { setError('Les offres n’ont pas pu être chargées.'); } finally { setLoading(false); } }
  useEffect(() => { let active = true; offresApi.listAll().then((result) => { if (active) { setData(result); setSelectedId(result.offers[0]?.id || null); } }).catch(() => { if (active) setError('Les offres n’ont pas pu être chargées.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const selectedRecord = data.offers.find((offer) => offer.id === selectedId);
  const selected = useMemo(() => selectedRecord ? { ...selectedRecord, conditions: data.conditions } : null, [selectedRecord, data.conditions]);
  const lot = useMemo(() => data.lots.find((item) => Number(item.id) === Number(selected?.lot_id)), [data.lots, selected]);
  async function saveOffer(payload) { setPending(true); try { const response = editor?.id ? await offresApi.updateOffer(editor.id, payload) : await offresApi.createOffer(payload); await load(); setSelectedId(response.data.id); setEditor(null); } catch { setError('L’offre n’a pas pu être enregistrée.'); } finally { setPending(false); } }
  return <div className="space-y-5 animate-enter"><Breadcrumb items={['Accueil', 'Offres', selected ? 'Fiche actif' : '']}/><PageHeader eyebrow="Commercialisation" title="Offres" description="Consultez toutes les informations utiles d’un actif dans une fiche unique." actions={<><Button variant="secondary" onClick={load}><RefreshCw size={16}/>Actualiser</Button><Button onClick={() => setEditor({})}><Plus size={17}/>Nouvelle offre</Button></>}/>{error && <Notification title="Action impossible" description={error}/>} {loading ? <Loader label="Chargement des offres…"/> : data.offers.length === 0 ? <EmptyState title="Aucune offre dans votre périmètre" description="Créez une offre à partir d’un lot patrimonial." action={<Button onClick={() => setEditor({})}><Plus size={16}/>Créer une offre</Button>}/> : <div className="grid gap-4 2xl:grid-cols-[260px_1fr]"><Card className="h-fit p-2"><p className="px-3 pb-2 pt-1 text-xs font-bold uppercase tracking-wider text-oriana-discret">Toutes les offres</p><div className="space-y-1">{data.offers.map((offer) => <button key={offer.id} aria-pressed={offer.id === selectedId} onClick={() => setSelectedId(offer.id)} className={`w-full rounded-oriana border p-3 text-left ${offer.id === selectedId ? 'border-oriana-lavande bg-oriana-violet/15' : 'border-transparent hover:bg-oriana-surfaceAlt'}`}><span className="flex items-center gap-2 text-sm font-semibold"><BadgeEuro size={16} className="text-oriana-lavande"/>{offer.nom || offer.numero || `Offre #${offer.id}`}</span><span className="mt-1 block text-xs text-oriana-discret">{natureLabels[offer.nature]}</span></button>)}</div></Card>{selected && <RichOfferDetail selected={selected} lot={lot} onEdit={() => setEditor(selected)}/>}</div>}<Drawer open={Boolean(editor)} onClose={() => !pending && setEditor(null)} title={editor?.id ? `Modifier ${editor.nom || 'l’offre'}` : 'Créer une offre'}>{editor && <OfferEditor record={editor.id ? editor : null} lots={data.lots} pending={pending} onCancel={() => setEditor(null)} onSave={saveOffer}/>}</Drawer></div>;
}
